pipeline {
    agent {
        label "main"
    }
    stages {
        stage('Test App') {
            steps {
                sh 'echo Testing Successfull...'
            }
        }
        stage('build Docker Image') {
            steps {
                sh "cd ./app && sudo docker build . --tag diptichoudhary/${JOB_NAME}:${BUILD_NUMBER}"
            }
        }
        stage('Docker Push Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                    sudo docker login --username ${USERNAME} --password ${PASSWORD}
                    sudo docker push diptichoudhary/${JOB_NAME}:${BUILD_NUMBER}
                """
                }
            }
        }
        stage('Deploy to Docker swarm') {
            agent {
                label "docker-swarm-manager"
            }
            steps {
                sh """
                    sudo IMAGE_TAG=${BUILD_NUMBER} IMAGE_NAME=diptichoudhary/${JOB_NAME} docker stack deploy --compose-file ./deploy/docker-compose.yaml ${JOB_NAME}
                """
            }
        }
    }
}