pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo Testing Successfull...'
            }
        }
        stage('build Docker Image') {
            steps {
                sh "cd ./app && sudo docker build . --tag diptichoudhary/${JOB_NAME}:${BUILD_NUMBER}"
            }
        }
        stage('Docker Push Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                    sudo docker login --username ${USERNAME} --password ${PASSWORD}
                    sudo docker push diptichoudhary/${JOB_NAME}:${BUILD_NUMBER}
                """
                }
            }
        }
        stage('Deploy to Docker swarm') {
            steps {
                sh 'echo docker swarm'
            }
        }
    }
}