pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo Testing Successfull...'
            }
        }
        stage('build Docker Image') {
            steps {
                sh 'cd ./app && docker build .'
            }
        }
        stage('Docker Push Registry') {
            steps {
                sh 'echo docker login'
            }
        }
        stage('Deploy to Docker swarm') {
            steps {
                sh 'echo docker swarm'
            }
        }
    }
}