version: "3"

services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "80:5000"
    environment:
      - MYSQL_DATABASE_USER=root
      - MYSQL_DATABASE_PASSWORD=password
      - MYSQL_DATABASE_DB=userdb
      - MYSQL_DATABASE_HOST=db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/1.sql:ro  
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE  